export const berry = '#F69C8B'
export const birch = '#FBF5EB'
export const blueball = '#4E85BB'
export const forestFog = '#EBEFED'
export const goldenrod = '#F4BC55'
export const lichen = '#DBF5ED'
export const lilyGreen = '#B6EBDB'
export const mint = '#92E0C9'
export const moss = '#81A0A2'
export const parkGreen = '#034045'
export const pine = '#11784D'
export const poppy = '#C2352B'
export const seafoam = '#83C7B2'
export const softSandBrown = '#F4E8D9'
export const spruce = '#056F78'
export const white = '#FFFFFF'

//To Be removed
export const lightTan = '#dbd7c9'
export const greyBlue = '#819FA2'
export const red = '#D40B04'
export const midnightGreen = '#09585E'
export const offWhite = '#FBF5EB'
