export const parkGreen = '#034045'
export const spruce = '#056F78' // New
export const moss = '#81A0A2' // New
export const lilyGreen = '#B6EBDB'
export const mint = '#92E0C9' // New
export const lichen = '#DBF5ED' // New
export const softSandBrown = '#F4E9D9'
export const birch = '#FBF5EB' // Previously Named offWhite
export const berry = '#F69C8B' // New
export const blueball = '#4E85BB' // New
export const goldenrod = '#F4BC55' // New
export const forestFog = '#EBEFED' // New
export const pine = '#11784D' // New
export const poppy = '#C2352B' // New (replaced red)
export const seafoam = '#83C7B2' // New
export const white = '#FFFFFF'
export const lightTan = '#dbd7c9'
export const greyBlue = '#819FA2'
// export const softSandBrownOld = '#f4e8d9'
export const red = '#D40B04' // Replaced
export const midnightGreen = '#09585E'
export const offWhite = '#FBF5EB' // Replaced
